'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

export default function ProcessingPage() {
  const router = useRouter();
  const [status, setStatus] = useState('Genereren van je bio...');

  useEffect(() => {
    const processData = async () => {
      try {
        // Get answers and photo from sessionStorage
        const answersJson = sessionStorage.getItem('answers');
        const photo = sessionStorage.getItem('photo');

        if (!answersJson) {
          console.error('No answers found');
          router.push('/questions');
          return;
        }

        if (!photo) {
          console.error('No photo found');
          router.push('/photo');
          return;
        }

        const answers = JSON.parse(answersJson);

        // Step 1: Use fixed bio text (always)
        setStatus('Voorbereiden van je bio...');
        const bio = `Hij verschijnt als de Vibecaster, een hybride tussen technomancer en sterrenwandelaar. In zijn kern draagt hij een dubbele ziel: één van pure logica die lichtcirkels van code weeft, en één van diepgevoelde energie waarmee hij emoties leest als gloeiende runes. Hij bezit een Stille Intensiteit, een aura die ruimtes vertraagt en verborgen waarheden zichtbaar maakt. Zijn reizen door verre landen gaven hem Natuurresonantie, waardoor hij rust en kracht kan oproepen uit elke omgeving. Zijn eeuwige zoektocht naar betekenis vormt zijn Visionaire Drift, een vermogen om mogelijke toekomsten te zien voordat ze ontstaan. In gevechten vertrouwt hij op Flowcraft, een staat waarin denken, voelen en creëren samensmelten tot één puls van kracht.`;
        
        console.log('Using fixed bio text');

        // Step 2: Generate follow-up questions with Gemini
        setStatus('Genereren van vervolgvragen...');
        let questions: string[] = [];
        
        try {
          const questionsResponse = await fetch('/api/gemini/questions', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({ bio }),
          });

          if (questionsResponse.ok) {
            const result = await questionsResponse.json();
            questions = result.questions;
            console.log('Questions generated by Gemini:', questions);
          } else {
            throw new Error('Questions API failed');
          }
        } catch (error) {
          console.warn('⚠️ [FALLBACK] Questions generation failed, using placeholders:', error);
          // Fallback questions
          questions = [
            'Wat geeft jou vandaag het meeste energie?',
            'Hoe zou jij je huidige vibe omschrijven aan iemand die je net ontmoet?',
            'Waar voel jij dat je nu naar op weg bent?',
            'Wat heeft jou gemaakt tot wie je nu bent?',
            'Wat is voor jou het belangrijkste in verbinding met anderen?',
          ];
        }

        // Step 3: Transform image with FAL
        setStatus('Transformeren van je foto...');
        let transformedImage: string | null = null;
        
        try {
          const falResponse = await fetch('/api/fal/transform', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({ photo, bio }),
          });

          if (falResponse.ok) {
            const result = await falResponse.json();
            transformedImage = result.image;
            console.log('Image transformed successfully');
          } else {
            // Try to get error details, but don't fail completely
            const errorData = await falResponse.json().catch(() => ({}));
            console.warn('⚠️ [FALLBACK] FAL transform failed, but continuing:', errorData);
            // Use original photo as fallback
            transformedImage = photo;
          }
        } catch (error) {
          console.warn('⚠️ [FALLBACK] FAL transform error, using original photo:', error);
          // Use original photo as fallback instead of failing completely
          transformedImage = photo;
        }

        // Store results in sessionStorage (always store, even if some steps had fallbacks)
        sessionStorage.setItem('bio', bio);
        sessionStorage.setItem('questions', JSON.stringify(questions));
        if (transformedImage) {
          sessionStorage.setItem('transformedImage', transformedImage);
        }

        // Navigate to result page (always navigate, even with fallbacks)
        router.push('/result');
      } catch (error) {
        console.error('❌ [CRITICAL] Processing error:', error);
        setStatus('Er ging iets mis. Probeer het opnieuw...');
        // Only redirect on critical errors
        setTimeout(() => {
          router.push('/photo');
        }, 3000);
      }
    };

    processData();
  }, [router]);

  return (
    <div className="flex min-h-screen items-center justify-center px-4">
      <div className="flex flex-col items-center gap-4">
        <div className="relative">
          <div className="h-16 w-16 animate-spin rounded-full border-4 border-white/20 border-t-[#F97068]"></div>
        </div>
        <p className="text-lg text-[#F5E8DC]/90 font-medium">
          {status}
        </p>
      </div>
    </div>
  );
}

